/******************************************************************************/
#include "stdafx.h"
#include "@@headers.h"
/******************************************************************************/
// this file WAS generated by Esenthel Engine Editor originally as Auto.cpp, but we are now free to make changes as needed
// since we are now using CMake + CLion instead of the Esenthel code editor.


const bool PUBLISH          =true; // this is set to true when compiling for publishing (use Bin/*.pak files)
cchar *C    ENGINE_DATA_PATH= PUBLISH ? u"Bin/Engine.pak"  : u"/home/ubuntu/EsenthelEngine/Editor/Bin/Engine.pak";
cchar *C   PROJECT_DATA_PATH= PUBLISH ? u"Bin/Project.pak" : u"/home/ubuntu/EsenthelEngine/Editor/Projects/541oob6a_h_5el6-6!zan_50/Game";
Cipher *C  PROJECT_CIPHER   =null;

void INIT()
{
   INIT_OBJ_TYPE(); // initialize object type enum
   LoadEmbeddedPaks(PROJECT_CIPHER); // load data embedded in Application executable file
   Paks.add(ENGINE_DATA_PATH); // load engine data

   if (PUBLISH) {
      Paks.add(PROJECT_DATA_PATH, PROJECT_CIPHER);
   } else {
      DataPath(PROJECT_DATA_PATH);
   }
}
void INIT_OBJ_TYPE() // this function will set up 'ObjType' enum used for object types
{
   Enum::Elm elms[]= // list of Editor created Object Classes
   {
      {"OBJ_CHR"         , UID(3377718608, 1157290285, 1449883574, 2193875233)},
      {"OBJ_DESTRUCTIBLE", UID(3862197110, 1100685637, 2030254268, 2407228583)},
      {"OBJ_ITEM"        , UID(1347336143, 1270230391, 3653824415, 3844916636)},
      {"OBJ_LIGHT_POINT" , UID(3609005105, 1118058365, 577565335, 3982143695)},
      {"OBJ_PARTICLES"   , UID(2721776529, 1227196451, 2852647815, 3333460217)},
   };
   ObjType.create("OBJ_TYPE", elms); // create 'ObjType' enum
}
