/******************************************************************************/
#include "stdafx.h"
#include "@@headers.h"
/******************************************************************************/
// THIS IS AN AUTOMATICALLY GENERATED FILE
// THIS FILE WAS GENERATED BY TITAN EDITOR, ACCORDING TO PROJECT SETTINGS
/******************************************************************************/
// CONSTANTS
/******************************************************************************/
#define    STEAM   0 // if Application properties have Steam enabled
#define    OPEN_VR 0 // if Application properties have OpenVR enabled
const bool PUBLISH          =true; // this is set to true when compiling for publishing
const bool EMBED_ENGINE_DATA=(false && !WINDOWS_NEW && !MOBILE && !WEB); // this is set to true when "Embed Engine Data" was enabled in application settings, this is always disabled for WindowsNew, Mobile and Web builds
cchar *C    ENGINE_DATA_PATH=((WINDOWS_NEW || MOBILE || WEB) ? u"Engine.pak"  : PUBLISH ? u"Bin/Engine.pak"  : u"/home/ubuntu/EsenthelEngine/Editor/Bin/Engine.pak");
cchar *C   PROJECT_DATA_PATH=((WINDOWS_NEW || MOBILE || WEB) ? u"Project.pak" : PUBLISH ? u"Bin/Project.pak" : u"/home/ubuntu/EsenthelEngine/Editor/Projects/541oob6a_h_5el6-6!zan_50/Game");
cchar *C   PROJECT_NAME     =u"Tutorials";
cchar *C   APP_NAME         =u"1 - Basic App";
const UID  APP_GUI_SKIN     =UID(0, 0, 0, 0);
Cipher *C  PROJECT_CIPHER   =null;
/******************************************************************************/
// FUNCTIONS
/******************************************************************************/
void INIT(bool load_engine_data, bool load_project_data)
{
   App.name(APP_NAME); // set application name
   INIT_OBJ_TYPE(); // initialize object type enum
   LoadEmbeddedPaks(PROJECT_CIPHER); // load data embedded in Application executable file
   if(load_engine_data )if(!EMBED_ENGINE_DATA)Paks.add(ENGINE_DATA_PATH); // load engine data
   if(load_project_data) // load project data
   {
      if(WINDOWS_NEW || MOBILE || WEB || PUBLISH)Paks.add(PROJECT_DATA_PATH, PROJECT_CIPHER);else DataPath(PROJECT_DATA_PATH);
   }
}
void INIT_OBJ_TYPE() // this function will setup 'ObjType' enum used for object types
{
   Enum::Elm elms[]= // list of Editor created Object Classes
   {
      {"OBJ_CHR"         , UID(3377718608, 1157290285, 1449883574, 2193875233)},
      {"OBJ_DESTRUCTIBLE", UID(3862197110, 1100685637, 2030254268, 2407228583)},
      {"OBJ_ITEM"        , UID(1347336143, 1270230391, 3653824415, 3844916636)},
      {"OBJ_LIGHT_POINT" , UID(3609005105, 1118058365, 577565335, 3982143695)},
      {"OBJ_PARTICLES"   , UID(2721776529, 1227196451, 2852647815, 3333460217)},
   };
   ObjType.create("OBJ_TYPE", elms); // create 'ObjType' enum
}
/******************************************************************************/
// ENUMS
/******************************************************************************/

/******************************************************************************/
