name: Build & Latest Release (Linux + Windows)

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # ───────────────────────────────────────────────────────── build ──
  build:
    env:                       # make the short SHA available to all steps
      SHORT_SHA: ${{ github.sha }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            cfg:   linux-release
            build: linux-build
            isLinux: true
          - os: windows-2022
            cfg:   windows-release
            build: windows-build
            isLinux: false

    runs-on: ${{ matrix.os }}

    steps:
      # 1) checkout & dependencies (unchanged) ──────────────────────────
      - uses: actions/checkout@v4
      # … your Install-packages / MSVC / unzip steps unchanged …

      # 2) configure → build → ctest  (unchanged) ───────────────────────
      - name: Configure
        run: cmake --preset ${{ matrix.cfg }}
      - name: Build
        run: cmake --build --preset ${{ matrix.build }}
      - name: Run unit tests
        run: ctest --test-dir out/build/${{ matrix.cfg }} --output-on-failure

      # 3) package files, then create platform-specific archive ─────────
      - name: Package & archive (Linux)
        if: matrix.isLinux
        run: |
          set -euo pipefail
          STAGE=out/dist
          mkdir -p "$STAGE/Bin"

          cp "out/build/${{ matrix.cfg }}/apps/client/client"  "$STAGE/client"
          cp "out/build/${{ matrix.cfg }}/apps/server/server"  "$STAGE/server"
          cp assets/Engine.pak                                 "$STAGE/Bin/Engine.pak"
          cp assets/Project.pak                                "$STAGE/Bin/Project.pak"

          tar -czf "linux_binaries_${SHORT_SHA::8}.tar.gz" -C "$STAGE" .
      - name: Package & archive (Windows)
        if: matrix.os == 'windows-2022'
        shell: pwsh
        run: |
          $Stage = "out/dist"
          New-Item "$Stage/Bin" -ItemType Directory -Force | Out-Null

          Copy-Item "out/build/${{ matrix.cfg }}/apps/client/client.exe"  "$Stage/client.exe"
          Copy-Item "out/build/${{ matrix.cfg }}/apps/server/server.exe"  "$Stage/server.exe"
          Copy-Item "assets/Engine.pak"                                   "$Stage/Bin/Engine.pak"
          Copy-Item "assets/Project.pak"                                  "$Stage/Bin/Project.pak"

          Compress-Archive -Path "$Stage/*" -DestinationPath "windows_binaries_${env:SHORT_SHA:0:8}.zip"

      # 4) upload just the finished archive as the artifact ─────────────
      - name: Upload platform archive
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: |
            linux_binaries_*.tar.gz
            windows_binaries_*.zip
          retention-days: 2

  # ───────────────────────────────────────────────────── release ──
  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download platform archives
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          merge-multiple: true      # puts both archives into release/
          path: release

      - name: Build release metadata
        id: vars
        run: |
          echo "timestamp=$(date -u +'%Y-%m-%d %H:%M UTC')" >> $GITHUB_OUTPUT
          echo "short_sha=${GITHUB_SHA::8}"                 >> $GITHUB_OUTPUT

      - name: Publish Latest release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          make_latest: true
          name: Latest build – ${{ steps.vars.outputs.timestamp }}
          body: |
            Automatic build from commit \
            [`${{ steps.vars.outputs.short_sha }}`]\
            (${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}).
          files: release/**
